#!/bin/zsh

# Check if the first argument is provided
if [ -z "$1" ]; then
    echo "Usage: $0 <first_argument>"
    exit 1
fi

# Extract the first argument
var1=$1

# Extract the substring before '.'
var2=${var1%%.*}

nasm -f elf64 "../../../x64-lib/brkalloc.asm" -o "../lib/brkalloc.o"

# Compile using gcc
gcc "$var1" "../lib/brkalloc.o" -z noexecstack -o "$var2"
